apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-clone-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: hotstar-clone
  template:
    metadata:
      labels:
        app: hotstar-clone
    spec:
      containers:
      - name: hotstar-clone
        image: vaibhavcheif/hotstardevsecops:latest
        ports:
        - containerPort: 3000
