apiVersion: v1
kind: Service
metadata:
  name: hotstar-clone-service
spec:
  selector:
    app: hotstar-clone   # must match the label in your Deployment
  ports:
    - protocol: TCP
      port: 3000         # service port
      targetPort: 3000   # container port
  type: NodePort         # exposes it on a port accessible via Minikube
